// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import type { RequestMethod } from 'umi-request';
import { getInstance, getMethods } from './instance';
import { get as GetType, post as PostType } from './types';

const URL_PREFIX = '';

const request = getInstance({
  prefix: '',
}) as RequestMethod;

const { get, post, put, del } = getMethods(request);

export {
  URL_PREFIX,
  request,
  get,
  post,
  put,
  del,
}
