// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import dayjs from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs';
import antdPlugin from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+antd-dayjs-webpack-plugin@1.0.6_dayjs@1.11.7/node_modules/antd-dayjs-webpack-plugin/src/antd-plugin.js';

import isSameOrBefore from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/isSameOrBefore';
import isSameOrAfter from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/isSameOrAfter';
import advancedFormat from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/advancedFormat';
import customParseFormat from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/customParseFormat';
import weekday from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/weekday';
import weekYear from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/weekYear';
import weekOfYear from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/weekOfYear';
import isMoment from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/isMoment';
import localeData from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/localeData';
import localizedFormat from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+dayjs@1.11.7/node_modules/dayjs/plugin/localizedFormat';

dayjs.extend(isSameOrBefore);
dayjs.extend(isSameOrAfter);
dayjs.extend(advancedFormat);
dayjs.extend(customParseFormat);
dayjs.extend(weekday);
dayjs.extend(weekYear);
dayjs.extend(weekOfYear);
dayjs.extend(isMoment);
dayjs.extend(localeData);
dayjs.extend(localizedFormat);

dayjs.extend(antdPlugin);
