// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-subapp/src/.umi-test/plugin-initialstate/@@initialState';
import model_2 from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-subapp/src/.umi-test/plugin-qiankun-slave/qiankunModel';

export const models = {
model_1: { namespace: '@@initialState', model: model_1 },
model_2: { namespace: '@@qiankunStateFromMaster', model: model_2 },
} as const
