// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.66_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
