// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// Created by Umi Plugin

export interface IConfigFromPluginsJoi {
moment2dayjs?: ({
preset?: string
plugins?: unknown[]
} | boolean)
szh5?: ({
debug?: boolean
zlb?: boolean
zzd?: boolean
history?: string
publicPath?: string
onlyChunkHash?: boolean
errorPages?: boolean
} | boolean)
szrequest?: ({
prefix?: ""
proxyTarget?: string
prefixTarget?: string
} | boolean)
initialstate?: ({
loading?: string
} | boolean)
model?: ({
extraModels?: string[]
excludeModels?: string[]
} | boolean)
}
