// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// Created by Umi Plugin

export interface IConfigFromPluginsJoi {
antd?: ({
configProvider?: {

}
dayjs?: boolean
dark?: boolean
compact?: boolean
import?: boolean
style?: ("less" | "css")
} | boolean)
szapp?: ({
debug?: boolean
zwfw?: boolean
zzd?: boolean
history?: string
publicPath?: string
onlyChunkHash?: boolean
errorPages?: boolean
} | boolean)
szrequest?: ({
prefix?: ""
proxyTarget?: string
prefixTarget?: string
} | boolean)
initialstate?: ({
loading?: string
} | boolean)
szlayout?: ({
wrapper?: string
base?: string
menusBase?: string
excludes?: unknown[]
layout?: string
breadcrumbsMode?: string
doNotRenderBreadcrumbs?: boolean
title?: string
logo?: string
copyright?: string
} | boolean)
model?: ({
extraModels?: string[]
excludeModels?: string[]
} | boolean)
qiankun?: ({
slave?: {

}
master?: {

}
externalQiankun?: boolean
} | boolean)
szsubapp?: {
name?: string
publicPath?: string
proxyTarget?: string
}
}
