// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"","title":"首页","menu":true,"icon":"HeatMapOutlined","parentId":"2","id":"1","originPath":"/"},"2":{"path":"/","isWrapper":true,"id":"2"},"3":{"path":"*","redirect":"/","id":"3"},"403":{"id":"403","path":"/403","exact":true},"404":{"id":"404","path":"/404","exact":true},"500":{"id":"500","path":"/500","exact":true}} as const;
  return {
    routes,
    routeComponents: {
'1': require('@/pages/home/index.tsx').default,
'2': require('@/wrappers/LoginWrapper/index.tsx').default,
'3': require( './EmptyRoute').default,
'403': require('D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-szapp/403/index.tsx').default,
'404': require('D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-szapp/404/index.tsx').default,
'500': require('D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-szapp/500/index.tsx').default,
},
  };
}
