// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export const DEPLOY_ENV = process.env.DEPLOY_ENV;
export const NODE_ENV = process.env.NODE_ENV;
export const DEPLOY_REGION = process.env.DEPLOY_REGION;
export const IS_PROD = DEPLOY_ENV === 'prod';
export const IS_DEV = DEPLOY_ENV !== 'prod';
export const IS_LOCAL = NODE_ENV !== 'production';
/**
 * 是否在浙里办中
 */
export const IS_IN_ZLB = navigator.userAgent.toLocaleLowerCase().match('dtdreamweb');
/**
 * 是否在支付宝中
 */
export const IS_IN_ALIPAY = navigator.userAgent.toLocaleLowerCase().match('aliapp');
/**
 * 是否在微信中
 */
export const IS_IN_WECHAT = navigator.userAgent.toLocaleLowerCase().match('micromessenger');
/**
 * 是否在浙里办或支付宝或微信中
 */
export const IS_IN_ZLB_OR_ALIPAY_OR_WECHAT = IS_IN_ZLB || IS_IN_ALIPAY || IS_IN_WECHAT;
/**
 * 是否在浙政钉中
 */
export const IS_IN_ZZD = navigator.userAgent.toLocaleLowerCase().match('zhejiang')
