// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { LayoutProps } from '@szzj/layout';

export type Route = {
  key: string;
  path: string;
  target?: string;
  wrappers?: string[];
  component?: string;
  menu?: boolean;
  title?: string;
  icon?: string;
  routes?: Route[];
};

export type { LayoutProps };
