// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.66_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.66_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/node_modules/.pnpm/registry.npmmirror.com+umi@4.0.66_5bmvg4qsmg6egghq5i32non7ji/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Provider, useModel } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-model';
export { DEPLOY_ENV, NODE_ENV, DEPLOY_REGION, IS_PROD, IS_DEV, IS_LOCAL, IS_IN_ZLB, IS_IN_ALIPAY, IS_IN_WECHAT, IS_IN_ZLB_OR_ALIPAY_OR_WECHAT, IS_IN_ZZD } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-region';
export { useModal, useList, useTree, useForm, useFetch, useTable } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-szhooks';
export { URL_PREFIX, request, get, post, put, del } from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-szrequest';
// plugins types.d.ts
export * from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-szhooks/types.d';
export * from 'D:/sourcecode/frontend/fed/szzj-umi-plugins/packages/template-pc/src/.umi-test/plugin-szrequest/types.d';
